// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interface.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 包含块高的一个请求消息
type BlockHeightRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeightRequest) Reset()         { *m = BlockHeightRequest{} }
func (m *BlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*BlockHeightRequest) ProtoMessage()    {}
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef53c9e620778f1, []int{0}
}

func (m *BlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeightRequest.Unmarshal(m, b)
}
func (m *BlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *BlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeightRequest.Merge(m, src)
}
func (m *BlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_BlockHeightRequest.Size(m)
}
func (m *BlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeightRequest proto.InternalMessageInfo

func (m *BlockHeightRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 包含块高的响应消息
type BlockHeightReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeightReply) Reset()         { *m = BlockHeightReply{} }
func (m *BlockHeightReply) String() string { return proto.CompactTextString(m) }
func (*BlockHeightReply) ProtoMessage()    {}
func (*BlockHeightReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ef53c9e620778f1, []int{1}
}

func (m *BlockHeightReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeightReply.Unmarshal(m, b)
}
func (m *BlockHeightReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeightReply.Marshal(b, m, deterministic)
}
func (m *BlockHeightReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeightReply.Merge(m, src)
}
func (m *BlockHeightReply) XXX_Size() int {
	return xxx_messageInfo_BlockHeightReply.Size(m)
}
func (m *BlockHeightReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeightReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeightReply proto.InternalMessageInfo

func (m *BlockHeightReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockHeightRequest)(nil), "pb.BlockHeightRequest")
	proto.RegisterType((*BlockHeightReply)(nil), "pb.BlockHeightReply")
}

func init() { proto.RegisterFile("interface.proto", fileDescriptor_3ef53c9e620778f1) }

var fileDescriptor_3ef53c9e620778f1 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcc, 0x2b, 0x49,
	0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0xd2, 0xe0, 0x12, 0x72, 0xca, 0xc9, 0x4f, 0xce, 0xf6, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x09, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x74, 0xb8, 0x04, 0x50, 0x54, 0x16, 0xe4, 0x54, 0x0a,
	0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xc3, 0x94, 0xc2, 0xb8, 0x46, 0x1e, 0x5c,
	0xec, 0x8e, 0x05, 0x05, 0x99, 0x79, 0x69, 0xf9, 0x42, 0xb6, 0x5c, 0xdc, 0x48, 0x1a, 0x85, 0xc4,
	0xf4, 0x0a, 0x92, 0xf4, 0x30, 0xed, 0x94, 0x12, 0xc1, 0x10, 0x2f, 0xc8, 0xa9, 0x54, 0x62, 0x48,
	0x62, 0x03, 0x3b, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x62, 0x2a, 0x5a, 0xbf, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppinfoClient is the client API for Appinfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppinfoClient interface {
	// BlockHeight 方法
	BlockHeight(ctx context.Context, in *BlockHeightRequest, opts ...grpc.CallOption) (*BlockHeightReply, error)
}

type appinfoClient struct {
	cc *grpc.ClientConn
}

func NewAppinfoClient(cc *grpc.ClientConn) AppinfoClient {
	return &appinfoClient{cc}
}

func (c *appinfoClient) BlockHeight(ctx context.Context, in *BlockHeightRequest, opts ...grpc.CallOption) (*BlockHeightReply, error) {
	out := new(BlockHeightReply)
	err := c.cc.Invoke(ctx, "/pb.Appinfo/BlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppinfoServer is the server API for Appinfo service.
type AppinfoServer interface {
	// BlockHeight 方法
	BlockHeight(context.Context, *BlockHeightRequest) (*BlockHeightReply, error)
}

// UnimplementedAppinfoServer can be embedded to have forward compatible implementations.
type UnimplementedAppinfoServer struct {
}

func (*UnimplementedAppinfoServer) BlockHeight(ctx context.Context, req *BlockHeightRequest) (*BlockHeightReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockHeight not implemented")
}

func RegisterAppinfoServer(s *grpc.Server, srv AppinfoServer) {
	s.RegisterService(&_Appinfo_serviceDesc, srv)
}

func _Appinfo_BlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppinfoServer).BlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Appinfo/BlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppinfoServer).BlockHeight(ctx, req.(*BlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Appinfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Appinfo",
	HandlerType: (*AppinfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlockHeight",
			Handler:    _Appinfo_BlockHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface.proto",
}
